# Generated by Django 4.1.6 on 2023-03-29 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='feature',
        ),
    ]
