# Generated by Django 4.1.6 on 2023-04-25 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='moyenne_annuelle',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
